### ISSUE TITLE
how to recreate src/resources ?

### ISSUE THREAD

**Issue by noud** [Agontuk/schema-builder#7]
hi,

i did made some changes and additions to schema-designer.
this does work okay.

now how do i get the work of schema-designer project
into the src/resources folder of this project?

i see schema-designer its output is
hashed and chunked and this one is not.

**Comment by Agontuk** [comment]
Make a PR to the schema-designer repo. If it gets merged, I'll update the bundle here.

**Comment by noud** [comment]
no please,

the thing is i want to try out things myself as well.
and maybe also run some changes you would not
like and accept to get merged.

i real would like to know how i'd 'roll my own' and do it myself.

would you be so kind to show me and others how that is done?

**Comment by noud** [comment]
no please,

the thing is i want to try out things myself as well.
and maybe also run some changes you would not
like and accept to get merged.

i real would like to know how i'd 'roll my own' and do it myself.

would you be so kind to show me and others how that is done?

**Comment by Agontuk** [comment]
Make your changes in schema-designer, then build it and copy/paste it to the schema-builder package. That's it.

**Comment by noud** [comment]
o lovely, i'll try tomorrow morning/upcomming saturday

(i changed  colors to ccs2.1 and more)

small question, i did see you first had the export being a .json
and turned that into .txt later on. why?
to me an export file having json to be .json sounds far more logical.
plus then all tools, f.i. Eclipse or Visual Studio Code open up the
correct fitting editor. Is that not an outstanding plus??

**Comment by noud** [comment]
and is what i somehow expected, copy/paste ;)

**Comment by Agontuk** [comment]
One of the user had an issue with not being able to import .json files. That's why I changed it. But I still prefer exporting as json file.
